In [2]:
import pandas as pd

# load data into a pandas dataframe
df = pd.read_csv('/Users/maram/Desktop/stats projects/Preliminary college year.csv')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
df.head()

,High School GPA,SAT Score,Federal Ethnic Group,Gender,Pell Grant Eligible,Attended Orientation,Attended Experience Day,Resident/Commuter,Athlete,Completed Summer Bridge,Dropout Proneness,Predicted Academic Difficulty,Educational Stress,Receptivity to Institutional Help,Receptivity to Academic Assistance,Receptivity to Personal Counseling,Receptivity to Social Engagement,Receptivity to Career Guidance,Receptivity to Financial Guidance,Desire to Transfer,Completed Campus Event Requirement,Completed Community Service Requirement,Number of Faculty Advisor Meetings Attended,Number of Peer Mentor Meetings Attended,Number of Workshops Attended,F17 GPA,S18 GPA,CUM GPA,Number of Credits Earned,Completed Connect,Reason for not Completing Connect,Retained F17-F18,Reason not Retained
0,2.595,970.0,White,F,0.0,1.0,0.0,1.0,1.0,2.0,55.0,86.0,33.0,53.0,25.0,30.0,94.0,60.0,50.0,82.0,0.0,1.0,5.0,2.0,2.0,0.660,2.20,1.788,18.0,0.0,academic dismissal after S18 semester,0.0,academic dismissal after S18 semester
1,2.637,1020.0,White,F,0.0,1.0,0.0,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,3.0,1.0,2.0,1.567,1.66,1.625,18.0,0.0,academic dismissal after S18 semester,0.0,academic dismissal after S18 semester
2,2.803,930.0,Black/African American,F,1.0,1.0,1.0,1.0,0.0,1.0,81.0,89.0,95.0,71.0,72.0,85.0,48.0,55.0,56.0,52.0,1.0,1.0,2.0,2.0,3.0,2.425,2.25,2.338,24.0,1.0,NaN,0.0,financial
3,2.354,1080.0,Hispanic/Latino,M,0.0,1.0,1.0,1.0,0.0,1.0,88.0,98.0,49.0,52.0,76.0,30.0,25.0,65.0,61.0,96.0,0.0,0.0,2.0,2.0,0.0,0.925,NaN,NaN,6.0,0.0,academic dismissal after F17 semester,0.0,academic dismissal after F17 semester
4,2.850,880.0,White,F,1.0,1.0,1.0,0.0,0.0,2.0,28.0,72.0,4.0,66.0,96.0,20.0,85.0,50.0,50.0,36.0,1.0,1.0,9.0,3.0,3.0,3.200,1.68,2.250,18.0,1.0,NaN,1.0,NaN

In [3]:
df.describe()

,ID,Age,Gender,Ethnicity,Marital,Livewith,Education,palpitations,orthopnea,chestpain,nausea,cough,fatigue,dyspnea,edema,PND,tightshoes,weightgain,DOE,delaydays
count,406.000000,406.000000,406.000000,406.000000,406.000000,404.000000,406.000000,406.000000,406.000000,406.000000,406.000000,406.000000,406.000000,406.000000,406.000000,406.000000,406.000000,406.000000,406.000000,403.000000
mean,127.926108,74.248768,1.448276,1.125616,1.665025,1.663366,2.118227,0.647783,1.637931,0.564039,0.502463,1.081281,1.950739,1.995074,1.226601,1.285714,0.839901,0.889163,1.738916,5.725779
std,102.176388,12.115073,0.497931,0.572181,0.703507,0.473144,1.373762,0.922467,1.148027,0.910616,0.812704,0.974132,0.867827,0.960954,1.140882,1.180978,1.040647,1.106671,1.025990,13.952903
min,1.000000,41.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,52.000000,67.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.500000
50%,103.500000,77.000000,1.000000,1.000000,2.000000,2.000000,2.000000,0.000000,2.000000,0.000000,0.000000,1.000000,2.000000,2.000000,1.000000,1.000000,0.000000,0.000000,2.000000,2.000000
75%,189.750000,84.000000,2.000000,1.000000,2.000000,2.000000,3.000000,1.000000,3.000000,1.000000,1.000000,2.000000,3.000000,3.000000,2.000000,2.000000,2.000000,2.000000,2.750000,7.000000
max,512.000000,96.000000,2.000000,5.000000,3.000000,2.000000,6.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,225.000000

# problem 1

The median number of delay days is 2. Build a logistic model to predict whether a person seeks medical treatment in 2 days or less (“1”) or takes longer than 2 days to seek medical treatment (“0”). Which factors does your model suggest are most useful in predicting the outcome.

In [7]:
df.fillna(df.median(numeric_only=True).round(1), inplace=True)
# Create a binary response variable based on the delaydays variable
df['seek_treatment_1'] = (df['delaydays'] <= 2.00).astype(int)
df.head()

,ID,Age,Gender,Ethnicity,Marital,Livewith,Education,palpitations,orthopnea,chestpain,nausea,cough,fatigue,dyspnea,edema,PND,tightshoes,weightgain,DOE,delaydays,seek_treatment,seek_treatment_1
0,1,77,2,1,3,1.0,2,2,2,3,2,1,3,3,1,0,0,0,0,0.041667,1,1
1,1,77,2,1,3,1.0,2,2,2,3,0,1,3,3,1,0,0,0,0,0.041667,1,1
2,2,61,2,1,1,2.0,2,0,3,0,3,0,0,3,3,0,0,3,0,0.165278,1,1
3,2,61,1,1,1,2.0,2,0,3,0,3,0,1,3,3,0,0,3,0,0.165278,1,1
4,3,50,1,3,1,2.0,3,0,2,0,0,0,3,2,1,2,3,3,3,0.494444,1,1

In [9]:
from sklearn.model_selection import train_test_split
X0 = df.iloc[:,1:19]
y0 = df['seek_treatment_1']
# split data into training and testing sets
X0_train, X0_test, y0_train, y0_test = train_test_split(X0,y0, test_size=0.2,random_state=43)

In [15]:

from sklearn.linear_model import LogisticRegression
# Fit a logistic regression model with delaydays as the predictor variable

logreg0 = LogisticRegression(max_iter=1000)
logreg0.fit(X0, y0)

LogisticRegression(max_iter=1000)

In [16]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

y0_pred = logreg0.predict(X0_test)
accuracy = accuracy_score(y0_test, y0_pred)
precision = precision_score(y0_test, y0_pred)
recall = recall_score(y0_test, y0_pred)
f1 = f1_score(y0_test, y0_pred)

print(f'Accuracy: {accuracy:.3f}')
print(f'Precision: {precision:.3f}')
print(f'Recall: {recall:.3f}')
print(f'F1 score: {f1:.3f}')

Accuracy: 0.671
Precision: 0.756
Recall: 0.680
F1 score: 0.716

In [21]:
# Identify important features
coefficients = pd.DataFrame({"feature": X0.columns, "coefficient": logreg0.coef_[0]})
coefficients = coefficients.sort_values(by="coefficient", ascending=False)
print("Important features:\n", coefficients)

Important features:
          feature  coefficient
16    weightgain     0.202886
6   palpitations     0.151952
8      chestpain     0.134731
15    tightshoes     0.124521
12       dyspnea     0.078355
3        Marital     0.073276
0            Age     0.011385
5      Education     0.010968
7      orthopnea    -0.032813
2      Ethnicity    -0.063375
9         nausea    -0.068425
1         Gender    -0.088329
14           PND    -0.167160
17           DOE    -0.179093
13         edema    -0.213623
11       fatigue    -0.224028
4       Livewith    -0.227679
10         cough    -0.331355

In [26]:
X1 = df[['weightgain', 'palpitations', 'chestpain', 'tightshoes', 'dyspnea', 'Marital', 'Age', 'cough', 'Livewith','fatigue', 'edema', 'DOE', 'PND','Gender' ]]
y1 = df['seek_treatment_1']
# split data into training and testing sets
X1_train, X1_test, y1_train, y1_test = train_test_split(X1,y1, test_size=0.2,random_state=43)

In [27]:
from sklearn.linear_model import LogisticRegression
# Fit a logistic regression model with delaydays as the predictor variable

logreg1 = LogisticRegression(max_iter=1000)
logreg1.fit(X1, y1)

LogisticRegression(max_iter=1000)

In [28]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

y1_pred = logreg1.predict(X1_test)
accuracy = accuracy_score(y1_test, y1_pred)
precision = precision_score(y1_test, y1_pred)
recall = recall_score(y1_test, y1_pred)
f1 = f1_score(y1_test, y1_pred)

print(f'Accuracy: {accuracy:.3f}')
print(f'Precision: {precision:.3f}')
print(f'Recall: {recall:.3f}')
print(f'F1 score: {f1:.3f}')

Accuracy: 0.683
Precision: 0.761
Recall: 0.700
F1 score: 0.729

note down the imporatance of computation, 
based on the coeff score and feature readability of log reg model we selected the variable with high coeff

# problem 2

How would your logistic model differ if it were to predict whether 

a person seeks medical treatment
                              on or less than the cohort average delay days (“1”), 
                                   or takes longer than the average number of days

to seek medical treatment (“0”)? Which factors does your model suggest are most useful in predicting the outcome.

for the given data the cohort average delay days is 5.698249

In [29]:
df2 = df.iloc[:,0:20]

In [30]:
df2.head()

,ID,Age,Gender,Ethnicity,Marital,Livewith,Education,palpitations,orthopnea,chestpain,nausea,cough,fatigue,dyspnea,edema,PND,tightshoes,weightgain,DOE,delaydays
0,1,77,2,1,3,1.0,2,2,2,3,2,1,3,3,1,0,0,0,0,0.041667
1,1,77,2,1,3,1.0,2,2,2,3,0,1,3,3,1,0,0,0,0,0.041667
2,2,61,2,1,1,2.0,2,0,3,0,3,0,0,3,3,0,0,3,0,0.165278
3,2,61,1,1,1,2.0,2,0,3,0,3,0,1,3,3,0,0,3,0,0.165278
4,3,50,1,3,1,2.0,3,0,2,0,0,0,3,2,1,2,3,3,3,0.494444

In [31]:
# Create a binary response variable based on the cohort average delaydays variable
df2['seek_treatment_1'] = (df2['delaydays'] <= 5.698249).astype(int)
df2.head()

,ID,Age,Gender,Ethnicity,Marital,Livewith,Education,palpitations,orthopnea,chestpain,nausea,cough,fatigue,dyspnea,edema,PND,tightshoes,weightgain,DOE,delaydays,seek_treatment_1
0,1,77,2,1,3,1.0,2,2,2,3,2,1,3,3,1,0,0,0,0,0.041667,1
1,1,77,2,1,3,1.0,2,2,2,3,0,1,3,3,1,0,0,0,0,0.041667,1
2,2,61,2,1,1,2.0,2,0,3,0,3,0,0,3,3,0,0,3,0,0.165278,1
3,2,61,1,1,1,2.0,2,0,3,0,3,0,1,3,3,0,0,3,0,0.165278,1
4,3,50,1,3,1,2.0,3,0,2,0,0,0,3,2,1,2,3,3,3,0.494444,1

In [32]:
from sklearn.model_selection import train_test_split
X2 = df2.iloc[:,1:19]
y2 = df2['seek_treatment_1']
# split data into training and testing sets
X2_train, X2_test, y2_train, y2_test = train_test_split(X2,y2, test_size=0.2,random_state=43)

In [33]:

from sklearn.linear_model import LogisticRegression
# Fit a logistic regression model with delaydays as the predictor variable

logreg2 = LogisticRegression(max_iter=1000)
logreg2.fit(X2, y2)

LogisticRegression(max_iter=1000)

In [34]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

y2_pred = logreg2.predict(X2_test)
accuracy = accuracy_score(y2_test, y2_pred)
precision = precision_score(y2_test, y2_pred)
recall = recall_score(y2_test, y2_pred)
f1 = f1_score(y2_test, y2_pred)

print(f'Accuracy: {accuracy:.3f}')
print(f'Precision: {precision:.3f}')
print(f'Recall: {recall:.3f}')
print(f'F1 score: {f1:.3f}')

Accuracy: 0.720
Precision: 0.725
Recall: 0.983
F1 score: 0.835

In logistic regression, the coefficient measures the change in the log-odds of the response variable for a one-unit change in the predictor variable, holding all other variables constant. A larger magnitude of the coefficient indicates a stronger association between the predictor variable and the response variable. 

Therefore, a variable with a large positive or negative coefficient is more likely to be an important predictor.

In [35]:
# Identify important features
coefficients = pd.DataFrame({"feature": X2.columns, "coefficient": logreg2.coef_[0]})
coefficients = coefficients.sort_values(by="coefficient", ascending=False)
print("Important features:\n", coefficients)

Important features:
          feature  coefficient
16    weightgain     0.144198
8      chestpain     0.095885
15    tightshoes     0.066541
11       fatigue     0.065849
7      orthopnea     0.038910
12       dyspnea     0.022761
4       Livewith     0.004861
5      Education     0.001740
0            Age     0.000172
2      Ethnicity    -0.005992
3        Marital    -0.012052
6   palpitations    -0.023553
1         Gender    -0.077842
10         cough    -0.099151
17           DOE    -0.164226
14           PND    -0.172513
9         nausea    -0.266234
13         edema    -0.288309

In [36]:
import pandas as pd

# create a dataframe from the coefficients
coef_df = pd.DataFrame({
    'feature': ['Age', 'Gender', 'Ethnicity', 'Marital', 'Livewith', 'Education',
                'palpitations', 'orthopnea', 'chestpain', 'cough', 'fatigue',
                'dyspnea', 'edema', 'nausea', 'PND', 'tightshoes', 'weightgain', 'DOE'],
    'coefficient': [0.000172, -0.077842, -0.005992, -0.012052, 0.004861, 0.001740,
                    -0.023553, 0.038910, 0.095885, -0.099151, 0.065849,
                    0.022761, -0.288309, -0.266234, -0.172513, 0.066541, 0.144198, -0.164226]
})

# rank the coefficients by their absolute values
coef_df['abs_coef'] = coef_df['coefficient'].abs()
ranked_coef = coef_df.sort_values('abs_coef', ascending=False)

# select the top 10 features with the largest coefficients
top10_features = ranked_coef.iloc[:10]['feature'].tolist()

print(top10_features)

['edema', 'nausea', 'PND', 'DOE', 'weightgain', 'cough', 'chestpain', 'Gender', 'tightshoes', 'fatigue']

In [37]:
X3 = df2[['edema', 'nausea', 'PND', 'DOE', 'chestpain', 'weightgain', 'cough', 'fatigue', 'tightshoes', 'Gender']
]

y3 = df2['seek_treatment_1']
# split data into training and testing sets
X3_train, X3_test, y3_train, y3_test = train_test_split(X3,y, test_size=0.2,random_state=43)

In [38]:
from sklearn.linear_model import LogisticRegression
# Fit a logistic regression model with delaydays as the predictor variable

logreg3 = LogisticRegression(max_iter=1000)
logreg3.fit(X3, y3)

LogisticRegression(max_iter=1000)

In [39]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

y3_pred = logreg3.predict(X3_test)
accuracy = accuracy_score(y3_test, y3_pred)
precision = precision_score(y3_test, y3_pred)
recall = recall_score(y3_test, y3_pred)
f1 = f1_score(y3_test, y3_pred)

print(f'Accuracy: {accuracy:.3f}')
print(f'Precision: {precision:.3f}')
print(f'Recall: {recall:.3f}')
print(f'F1 score: {f1:.3f}')

Accuracy: 0.598
Precision: 0.605
Recall: 0.980
F1 score: 0.748

It's important to keep in mind that feature selection based solely on the coefficient values can sometimes result in a less accurate model. In some cases, including less important features in the model can actually improve accuracy. Therefore, it's important to balance the trade-off between including all available features and only selecting the most important ones.
And, the accuracy of the logistic regression model can depend on many factors, including "the quality and amount of data, the distribution of the data, and the model's hyperparameters". Therefore, it's important to consider all of these factors and fine-tune the model accordingly.

# Problem 3

How would your logistic model differ if it were to predict whether a person seeks medical 
                            treatment on or less than 1 day (“1”) 
                                  or takes longer than 1 day to seek medical treatment (“0”)? 
Which factors does your model suggest are most useful in predicting the outcome.

In [40]:
df3 = df.iloc[:,0:20]

In [41]:
df3.head()

,ID,Age,Gender,Ethnicity,Marital,Livewith,Education,palpitations,orthopnea,chestpain,nausea,cough,fatigue,dyspnea,edema,PND,tightshoes,weightgain,DOE,delaydays
0,1,77,2,1,3,1.0,2,2,2,3,2,1,3,3,1,0,0,0,0,0.041667
1,1,77,2,1,3,1.0,2,2,2,3,0,1,3,3,1,0,0,0,0,0.041667
2,2,61,2,1,1,2.0,2,0,3,0,3,0,0,3,3,0,0,3,0,0.165278
3,2,61,1,1,1,2.0,2,0,3,0,3,0,1,3,3,0,0,3,0,0.165278
4,3,50,1,3,1,2.0,3,0,2,0,0,0,3,2,1,2,3,3,3,0.494444

In [42]:
# Create a binary response variable based on the cohort average delaydays variable
df3['seek_treatment_3'] = (df3['delaydays'] <= 1).astype(int)
df3.head()

,ID,Age,Gender,Ethnicity,Marital,Livewith,Education,palpitations,orthopnea,chestpain,nausea,cough,fatigue,dyspnea,edema,PND,tightshoes,weightgain,DOE,delaydays,seek_treatment_3
0,1,77,2,1,3,1.0,2,2,2,3,2,1,3,3,1,0,0,0,0,0.041667,1
1,1,77,2,1,3,1.0,2,2,2,3,0,1,3,3,1,0,0,0,0,0.041667,1
2,2,61,2,1,1,2.0,2,0,3,0,3,0,0,3,3,0,0,3,0,0.165278,1
3,2,61,1,1,1,2.0,2,0,3,0,3,0,1,3,3,0,0,3,0,0.165278,1
4,3,50,1,3,1,2.0,3,0,2,0,0,0,3,2,1,2,3,3,3,0.494444,1

In [43]:
from sklearn.model_selection import train_test_split
X4 = df3.iloc[:,1:19]
y4 = df3['seek_treatment_3']
# split data into training and testing sets
X4_train, X4_test, y4_train, y4_test = train_test_split(X4,y4, test_size=0.2,random_state=43)

In [44]:

from sklearn.linear_model import LogisticRegression
# Fit a logistic regression model with delaydays as the predictor variable

logreg4 = LogisticRegression(max_iter=500)
logreg4.fit(X4, y4)

LogisticRegression(max_iter=500)

In [45]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

y4_pred = logreg4.predict(X4_test)
accuracy = accuracy_score(y4_test, y4_pred)
precision = precision_score(y4_test, y4_pred)
recall = recall_score(y4_test, y4_pred)
f1 = f1_score(y4_test, y4_pred)

print(f'Accuracy: {accuracy:.3f}')
print(f'Precision: {precision:.3f}')
print(f'Recall: {recall:.3f}')
print(f'F1 score: {f1:.3f}')

Accuracy: 0.671
Precision: 0.583
Recall: 0.241
F1 score: 0.341

In [46]:
# Identify important features
coefficients = pd.DataFrame({"feature": X4.columns, "coefficient": logreg4.coef_[0]})
coefficients = coefficients.sort_values(by="coefficient", ascending=False)
print("Important features:\n", coefficients)

Important features:
          feature  coefficient
12       dyspnea     0.139578
16    weightgain     0.133620
11       fatigue     0.130957
14           PND     0.125841
6   palpitations     0.104412
3        Marital     0.081730
5      Education     0.060870
15    tightshoes     0.057531
1         Gender     0.042802
0            Age     0.014479
9         nausea    -0.000162
2      Ethnicity    -0.081069
8      chestpain    -0.137405
17           DOE    -0.253243
13         edema    -0.289665
7      orthopnea    -0.301267
10         cough    -0.313934
4       Livewith    -0.326833

In [47]:
import pandas as pd

# Creating the dataframe with coefficients
coef_df = pd.DataFrame( {'feature': ['dyspnea', 'weightgain', 'fatigue', 'PND', 'palpitations', 'Marital', 'Education', 'tightshoes', 'Gender', 'Age', 'nausea', 'Ethnicity', 'chestpain', 'DOE', 'edema', 'orthopnea', 'cough', 'Livewith'], 
                'coefficient': [0.139578, 0.133620, 0.130957, 0.125841, 0.104412, 0.081730, 0.060870, 0.057531, 0.042802, 0.014479, -0.000162, -0.081069, -0.137405, -0.253243, -0.289665, -0.301267, -0.313934, -0.326833]})


# rank the coefficients by their absolute values
coef_df['abs_coef'] = coef_df['coefficient'].abs()
ranked_coef = coef_df.sort_values('abs_coef', ascending=False)

# select the top 10 features with the largest coefficients
top10_features = ranked_coef.iloc[:10]['feature'].tolist()

print(top10_features)

['Livewith', 'cough', 'orthopnea', 'edema', 'DOE', 'dyspnea', 'chestpain', 'weightgain', 'fatigue', 'PND']

In [48]:
X5 = df3[['Livewith', 'cough', 'orthopnea', 'edema', 'DOE', 'dyspnea', 'chestpain', 'weightgain', 'fatigue', 'PND']
]

y5 = df3['seek_treatment_3']
# split data into training and testing sets
X5_train, X5_test, y5_train, y5_test = train_test_split(X5,y5, test_size=0.2,random_state=43)

In [49]:
from sklearn.linear_model import LogisticRegression
# Fit a logistic regression model with delaydays as the predictor variable

logreg5 = LogisticRegression(max_iter=1000)
logreg5.fit(X5, y5)

LogisticRegression(max_iter=1000)

In [50]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

y5_pred = logreg5.predict(X5_test)
accuracy = accuracy_score(y5_test, y5_pred)
precision = precision_score(y5_test, y5_pred)
recall = recall_score(y5_test, y5_pred)
f1 = f1_score(y5_test, y5_pred)

print(f'Accuracy: {accuracy:.3f}')
print(f'Precision: {precision:.3f}')
print(f'Recall: {recall:.3f}')
print(f'F1 score: {f1:.3f}')

Accuracy: 0.695
Precision: 0.700
Recall: 0.241
F1 score: 0.359

It is possible that removing some features that have low coefficients may have an impact on the overall performance of the logistic regression model. It is important to note that the coefficient of a feature only indicates its strength of association with the outcome variable, but it does not necessarily imply its importance in predicting the outcome.